
export interface full_AffiliateModel {
  id? : number ;
  lcUserName? : string ;
  lcPassword? : string ;
  lcConfirm? : string ;
  lcRegisterDate? : Date ;
  lcIsEnabled? : string ;
  lcFirstName? : string ;
  lcLastName? : string ;
  lcWebSite? : string ;
  lcCompany? : string ;
  lcAddress? : string ;
  lcDistrict? : string ;
  lcCity? : string ;
  lcCountry? : string ;
  lcState? : string ;
  lcZip? : string ;
  lcPhone? : string ;
  lcEmail? : string ;
  lcCommission? : string ;
}
export interface crud_AffiliateModel {
  id? : number ;
  lcUserName? : string ;
  lcPassword? : string ;
  lcConfirm? : string ;
  lcRegisterDate? : Date ;
  lcIsEnabled? : string ;
  lcFirstName? : string ;
  lcLastName? : string ;
  lcWebSite? : string ;
  lcCompany? : string ;
  lcAddress? : string ;
  lcDistrict? : string ;
  lcCity? : string ;
  lcCountry? : string ;
  lcState? : string ;
  lcZip? : string ;
  lcPhone? : string ;
  lcEmail? : string ;
  lcCommission? : string ;
}
export interface form_AffiliateModel {
  id? : number ;
  lcUserName? : string ;
  lcPassword? : string ;
  lcConfirm? : string ;
  lcRegisterDate? : Date ;
  lcIsEnabled? : string ;
  lcFirstName? : string ;
  lcLastName? : string ;
  lcWebSite? : string ;
  lcCompany? : string ;
  lcAddress? : string ;
  lcDistrict? : string ;
  lcCity? : string ;
  lcCountry? : string ;
  lcState? : string ;
  lcZip? : string ;
  lcPhone? : string ;
  lcEmail? : string ;
  lcCommission? : string ;
}
export interface post_AffiliateModel {
  id? : number ;
  lcUserName? : string ;
  lcPassword? : string ;
  lcConfirm? : string ;
  lcRegisterDate? : Date ;
  lcIsEnabled? : string ;
  lcFirstName? : string ;
  lcLastName? : string ;
  lcWebSite? : string ;
  lcCompany? : string ;
  lcAddress? : string ;
  lcDistrict? : string ;
  lcCity? : string ;
  lcCountry? : string ;
  lcState? : string ;
  lcZip? : string ;
  lcPhone? : string ;
  lcEmail? : string ;
  lcCommission? : string ;
}
export interface put_AffiliateModel {
  id? : number ;
  lcUserName? : string ;
  lcPassword? : string ;
  lcConfirm? : string ;
  lcRegisterDate? : Date ;
  lcIsEnabled? : string ;
  lcFirstName? : string ;
  lcLastName? : string ;
  lcWebSite? : string ;
  lcCompany? : string ;
  lcAddress? : string ;
  lcDistrict? : string ;
  lcCity? : string ;
  lcCountry? : string ;
  lcState? : string ;
  lcZip? : string ;
  lcPhone? : string ;
  lcEmail? : string ;
  lcCommission? : string ;
}