import { FormBuilder, FormGroup, Validators } from '@angular/forms';


export const formModel = {
  id: ['', Validators.required],
  lcBusinessName: ['', Validators.required],
  lcBusinessAddress: ['', Validators.required],
  lcBusinessCity: ['', Validators.required],
  lcBusinessState: ['', Validators.required],
  lcBusinessZip: ['', Validators.required],
  lcBusinessCountry: ['', Validators.required],
  uxBusinessPhoneNoteLabel: ['', Validators.required],
  lcBusinessFax: ['', Validators.required],
  lcBusinessEmail: ['', Validators.required],
  uxEnableMapLabel: ['', Validators.required],
  uxGoogleMapTypeLabel: ['', Validators.required],
  uxGoogleMapAPIKeyLabel: ['', Validators.required],
  uxLatitudeLabel: ['', Validators.required],
  uxLongitudeLabel: ['', Validators.required],
  uxEmailProviderLabel: ['', Validators.required],
  lcSmtpServer: ['', Validators.required],
  lcSmtpPort: ['', Validators.required],
  lcSmtpAuthenRequired: ['', Validators.required],
  uxRequireEmailSslLabel: ['', Validators.required],
  uxEnableFacebookPageLabel: ['', Validators.required],
  uxFacebookPageURLLabel: ['', Validators.required],
  uxLineEnabledLabel: ['', Validators.required],
  uxLineAccountLabel: ['', Validators.required],
  uxTwitterEnabledLabel: ['', Validators.required],
  uxTwitterUrlLabel: ['', Validators.required],
  uxInstagramEnabledLabel: ['', Validators.required],
  uxInstagramUrlLabel: ['', Validators.required],
  uxYoutubeEnabledLabel: ['', Validators.required],
  uxYoutubeUrlLabel: ['', Validators.required],
  uxFaceBookLikeButtonLabel: ['', Validators.required],
  uxLineItLabel: ['', Validators.required],
  uxTwitterTweetLabel: ['', Validators.required],
  uxZopimEnabledLabel: ['', Validators.required],
  uxFacebookMessengerEnabledLabel: ['', Validators.required],
  uxFacebookMessengerInfoLabel: ['', Validators.required],
  uxFacebookMessengerLabel: ['', Validators.required],
  uxFacebookCustomerLabel: ['', Validators.required],
  uxFacebookCustomerFanpageID: ['', Validators.required],
  uxFacebookCustomerAppID: ['', Validators.required],
  uxFacebookCustomerWelcomeNoteText: ['', Validators.required],
  uxOldPasswordLabel: ['', Validators.required],
  uxNewPasswordLabel: ['', Validators.required],
};
